version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    post_build:
      - "sphinx-build -b html docs/source docs/build/html"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/source/conf.py
