sensors_dict = {
    "SENTINEL2_L1C": {
        "sensor_biovar": ["Cab", "Cm", "Cw", "FVC", "LAI", "laiCab", "laiCm", "laiCw"],
        "scale_factor": 0.0001,
        "bandlist": [
            "B02",
            "B03",
            "B04",
            "B05",
            "B06",
            "B07",
            "B08",
            "B8A",
            "B11",
            "B12",
        ],
    },
    "SENTINEL2_L2A": {
        "sensor_biovar": [
            "Cab",
            "Cm",
            "Cw",
            "FVC",
            "LAI",
            "laiCab",
            "laiCm",
            "laiCw",
            "CNC_Cab",
            "CNC_Cprot",
            "mangrove_Cab",
            "mangrove_Cm",
            "mangrove_Cw",
            "mangrove_LAI",
        ],
        "scale_factor": 0.0001,
        "bandlist": [
            "B02",
            "B03",
            "B04",
            "B05",
            "B06",
            "B07",
            "B08",
            "B8A",
            "B11",
            "B12",
        ],
    },
    "SENTINEL3_OLCI_L1B": {
        "sensor_biovar": ["FAPAR", "FVC", "LAI", "LCC"],
        "scale_factor": 1,
        "bandlist": [
            "B01",
            "B02",
            "B03",
            "B04",
            "B05",
            "B06",
            "B07",
            "B08",
            "B09",
            "B10",
            "B11",
            "B12",
            "B13",
            "B14",
            "B15",
            "B16",
            "B17",
            "B18",
            "B19",
            "B20",
            "B21",
        ],
    },
    "LANDSAT8_L2": {
        "sensor_biovar": ["LAI"],
        "scale_factor": 0.00001,
        "bandlist": [
            "B02",
            "B03",
            "B04",
            "B05",
            "B06",
            "B07",
        ],
    },
}
